version: '3.4'

services:
  hazemjoined:
    image: hazemjoined
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 80:80
